# Generated by Django 3.0.3 on 2020-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200407_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
