# Generated by Django 3.0.5 on 2020-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
