# Generated by Django 3.0.5 on 2020-04-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_liked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='main.UserProfile'),
        ),
    ]
