# Generated by Django 3.0.5 on 2020-04-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200422_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked_user',
        ),
    ]
