# Generated by Django 3.0.5 on 2020-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_comment_liked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='media/images/profile/defaultPic.jpg', upload_to='images/profile'),
        ),
    ]
