# Generated by Django 3.0.5 on 2020-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200425_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default=' / home / mohamad / Documents / Django / commentie / media / images / profile / defaultPic.JPG', upload_to='images/profile'),
        ),
    ]
