# Generated by Django 3.0.5 on 2020-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200425_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default=' images / profile / defaultPic.JPG', upload_to='images/profile'),
        ),
    ]
