# Generated by Django 3.0.5 on 2020-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200425_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_photo',
            field=models.ImageField(default=' images / wall.JPG', upload_to='images'),
        ),
    ]
